{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "upnp-nat-controller.fullname" . }}-metrics
  labels:
    {{- include "upnp-nat-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "upnp-nat-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
{{- end }}
{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "upnp-nat-controller.fullname" . }}
  labels:
    {{- include "upnp-nat-controller.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "upnp-nat-controller.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
