apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: internetgatewaydevices.crd.nashes.uk
spec:
  conversion:
    strategy: None
  group: crd.nashes.uk
  names:
    kind: InternetGatewayDevice
    listKind: InternetGatewayDeviceList
    plural: internetgatewaydevices
    shortNames:
    - igd
    singular: internetgatewaydevice
  scope: Cluster
  versions:
  - name: v1alpha1
    additionalPrinterColumns:
    - name: DEVICE NAME
      type: string
      description: The name of the IGD
      jsonPath: .status.friendlyName
    - name: IP
      type: string
      description: The internal ip of the IGD
      jsonPath: .status.ip
    - name: EXTERNAL IP
      type: string
      description: The external ip of the IGD
      jsonPath: .status.externalIpAddress
    - name: UPTIME
      type: string
      description: The name of the IGD
      jsonPath: .status.uptime
    schema:
      openAPIV3Schema:
        description: An InternetGatewayDevice isn't a resource that should be created
          manually. It is created by the UPnP NAT Controller to track the state of
          an IGD on a network
        properties:
          status:
            description: The InternetGatewayDeviceStatus describes the status of an
              IGD
            properties:
              connectionStatus:
                description: The connection status of the IGD
                type: string
              externalIpAddress:
                description: External IP address of the IGD
                pattern: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$
                type: string
              friendlyName:
                description: The friendly name for the IGD
                type: string
              ip:
                description: IP address of the IGD
                pattern: ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$
                type: string
              portMappings:
                description: PortMappings contains a list of the current port mappings
                items:
                  description: PortMapping contains a single port mapping
                  properties:
                    enabled:
                      description: Is the mapping enabled
                      type: boolean
                    externalPort:
                      description: The external port receiving traffic
                      maximum: 65535
                      minimum: 1
                      type: integer
                    internalClient:
                      description: Where the traffic will be NATted to internally
                      pattern: ^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}){0,1}$
                      type: string
                    internalPort:
                      description: The port to connect to on the internalClient
                      maximum: 65535
                      minimum: 1
                      type: integer
                    leaseDuration:
                      description: Length of the lease in seconds
                      minimum: 0
                      type: integer
                    portMappingDescription:
                      description: Remote host for the mapping
                      type: string
                    protocol:
                      description: The protocol for the port mapping
                      enum:
                      - TCP
                      - UDP
                      type: string
                    remoteHost:
                      description: Remote host for the mapping
                      pattern: ^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}){0,1}$
                      type: string
                  type: object
                type: array
              totalBytesReceived:
                description: Total bytes received by the IGD
                minimum: 0
                type: integer
              totalBytesSent:
                description: Total bytes sent by the IGD
                minimum: 0
                type: integer
              totalPacketsReceived:
                description: Total packets received by the IGD
                minimum: 0
                type: integer
              totalPacketsSent:
                description: Total packets sent by the IGD
                minimum: 0
                type: integer
              uptime:
                description: The uptime of the IGD in seconds
                minimum: 0
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
