name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Vet
        run: go vet ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.8
      - name: Test
        run: make test
      - name: Coverage
        run: go tool cover -func=cover.out | tail -1
